version: "3.1"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7.31
    container_name: "todo_mysql"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    ports:
      - 3320:3306
    environment:
      MYSQL_ROOT_PASSWORD: Todo123@
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: Todo123@
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "todo_phpmyadmin"
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=Todo123@
    links:
      - mysql
    ports:
      - 8100:80

volumes:
  mysql:
